# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: build-all
  
  clean:
    requires:
      vars: [FUNC]
    cmds:
      - rm -rf dist/funcs/{{.FUNC}}/
    silent: true

  clean-all:
    cmds:
      - rm -rf dist/funcs/
    silent: true

  build:
    requires:
      vars: [FUNC]
    sources:
      - src/funcs/{{.FUNC}}/*.ts
    cmds:
      - npx tsx tasks/build.ts {{.FUNC}}
    generates:
      - dist/funcs/{{.FUNC}}/*.js

  build-all:
    vars:
      FUNC_NAMES:
        sh: |
          # ls -d src/funcs/*/
          npx tsx tasks/find-funcs.ts
    sources:
      - src/funcs/**/*.ts
    cmds:
      - for: { var: FUNC_NAMES }
        task: build
        vars: 
          FUNC: '{{ .ITEM }}'
    generates:
      - dist/funcs/**/*.js

  rebuild:
    deps: [clean]
    cmds:
      - task: build

  rebuild-all:
    deps: [clean-all]
    cmds:
      - task: build-all

  upload:
    deps: [build]
    cmds:
      - npx tsx tasks/upload.ts

  deploy:
    deps: [upload]
    cmds:
      - npx tsx tasks/deploy.ts
