# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: build all funcs.
    cmds:
      - task: build-all
  
  sdk:
    desc: aws sdk test.
    cmds:
      - npx tsx src/tasks/_awssdk.ts

  clean:*:
    desc: clean up artifact for specific func (* is func name).
    vars:
      FUNC: '{{ index .MATCH 0 }}'
    requires:
      vars: [ FUNC ]
    cmds:
      - rm -rf dist/funcs/{{ .FUNC }}/
    silent: true

  clean-all:
    desc: clean up all artifacts.
    cmds:
      - rm -rf dist/funcs/
    silent: true

  build:*:
    desc: build specific func (* is func name).
    vars:
      FUNC: '{{ index .MATCH 0 }}'
    requires:
      vars: [ FUNC ]
    sources:
      - src/funcs/{{ .FUNC }}/*.ts
    cmds:
      - npx tsx src/tasks/build.ts {{ .FUNC }}
    generates:
      - dist/funcs/{{ .FUNC }}/*.js

  build-all:
    desc: build all funcs.
    vars:
      FUNC_NAMES:
        sh: |
          # ls -d src/funcs/*/
          npx tsx src/tasks/find-funcs.ts
    sources:
      - src/funcs/**/*.ts
    cmds:
      - for: { var: FUNC_NAMES }
        task: build:{{ .ITEM }}
    generates:
      - dist/funcs/**/*.js

  rebuild:*:
    desc: rebuild specific func (* is func name).
    vars:
      FUNC: '{{ index .MATCH 0 }}'
    deps: 
      - clean:{{ .FUNC }}
    cmds:
      - task: build:{{ .FUNC }}

  rebuild-all:
    desc: rebuild all funcs.
    deps: 
      - clean-all
    cmds:
      - task: build-all

  package:*:
    desc: package specific func (* is func name).
    vars:
      FUNC: '{{ index .MATCH 0 }}'
    requires:
      vars: [ FUNC ]
    deps: 
      - build:{{ .FUNC }}
    sources:
      - dist/funcs/{{ .FUNC }}/*.js
    cmds:
      - npx tsx src/tasks/package.ts {{ .FUNC }}
    generates:
      - dist/packages/{{ .FUNC }}.zip

  package-all:
    desc: package all funcs.
    vars:
      FUNC_NAMES:
        sh: npx tsx src/tasks/find-funcs.ts
    cmds:
      - for: { var: FUNC_NAMES }
        task: package:{{ .ITEM }}

  sync-from-repo:*:
    desc: s3 sync checksum from func package repository to local (* is func name).
    vars:
      FUNC: '{{ index .MATCH 0 }}'
    requires:
      vars: [ FUNC ]
    cmds:
      - npx tsx src/tasks/sync-from-repo.ts {{ .FUNC }}
    silent: true

  upload:*:
    desc: upload specific func (* is func name).
    vars:
      FUNC: '{{ index .MATCH 0 }}'
    requires:
      vars: [ FUNC ]
    deps: 
      - package:{{ .FUNC }}
      - sync-from-repo:{{ .FUNC }}
    sources:
      - dist/packages/{{ .FUNC }}.zip
    cmds:
      - npx tsx src/tasks/upload.ts {{ .FUNC }}
    generates:
      - dist/uploads/**/{{ .FUNC }}.zip.checksum

  upload-all:
    desc: upload all funcs to S3.
    vars:
      FUNC_NAMES:
        sh: npx tsx src/tasks/find-funcs.ts
    cmds:
      - for: { var: FUNC_NAMES }
        task: upload:{{ .ITEM }}

  sync-from-code:*:
    desc: lambda sync code's sha256 from lambda to local (* is func name).
    vars:
      FUNC: '{{ index .MATCH 0 }}'
    requires:
      vars: [ FUNC ]
    cmds:
      - npx tsx src/tasks/sync-from-code.ts {{ .FUNC }}
    silent: false

  deploy:*:
    desc: deploy specific func (* is func name).
    vars:
      FUNC: '{{ index .MATCH 0 }}'
    requires:
      vars: [ FUNC ]
    deps: 
      - upload:{{ .FUNC }}
      - sync-from-code:{{ .FUNC }}
    sources:
      - dist/uploads/**/{{ .FUNC }}.zip.checksum
    cmds:
      - npx tsx src/tasks/deploy.ts {{ .FUNC }}
    generates:
      - dist/deploys/**/{{ .FUNC }}.codesha256

  deploy-all:
    desc: deploy all funcs in Lambda.
    vars:
      FUNC_NAMES:
        sh: npx tsx src/tasks/find-funcs.ts
    cmds:
      - for: { var: FUNC_NAMES }
        task: deploy:{{ .ITEM }}
