# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  
  ts_exec:
    cmds:
      - npx tsx src/index.ts

  loop_static:
    cmds:
      - for: [ '.gitignore' ]
        cmd: cat {{ .ITEM }}

  loop_matrix:
    vars:
      OS_VAR: [ 'linux', 'windows', 'darwin' ]
      ARCH_VAR: [ 'amd64', 'arm64' ]
    cmds:
      - for:
          matrix:
            OS: 
              ref: .OS_VAR
            ARCH:
              ref: .ARCH_VAR
        cmd: 
          echo "{{ .ITEM.OS }}/{{ .ITEM.ARCH }}"

  loop_sources:
    sources:
      - package.json
      - .gitignore
    cmds:
      - for: sources
        cmd: 
          cat {{ .ITEM }}

  clean:
    sources:
      - dist/*.js
      - dist/*.map
    cmds:
      - npx tsx tasks/clean.ts
      - rm -rf dist/

  build:
    sources:
      - src/*.ts
    cmds:
      - npx tsx tasks/build.ts
      - npx tsc
    generates:
      - dist/*.js

  rebuild:
    deps: [clean]
    cmds:
      - task: build

  upload:
    deps: [build]
    cmds:
      - npx tsx tasks/upload.ts

  deploy:
    deps: [upload]
    cmds:
      - npx tsx tasks/deploy.ts
