# https://taskfile.dev

version: '3'

dotenv:
  - .env

tasks:
  default:
    desc: build all funcs.
    cmds:
      - task: build-all
  
  sdk:
    desc: aws sdk test.
    cmds:
      - npx tsx src/tasks/_awssdk.ts

  install-deps:
    desc: install depending npm packages
    run: once
    status:
      - test -f node_modules/.installed
    cmds:
      - npm install
      - touch node_modules/.installed
    silent: false

  clean:*:
    desc: clean up artifact for specific func (* is func name).
    vars:
      FUNC: '{{index .MATCH 0}}'
    requires:
      vars: [FUNC]
    cmds:
      - rm -rf dist/funcs/{{.FUNC}}/
    silent: true

  clean-all:
    desc: clean up all artifacts.
    cmds:
      - rm -rf dist/funcs/
      - rm -rf node_modules/.installed
    silent: true

  build:*:
    desc: build specific func (* is func name).
    vars:
      FUNC: '{{index .MATCH 0}}'
    requires:
      vars: [FUNC]
    deps:
      - install-deps
    sources:
      - src/funcs/{{.FUNC}}/*.ts
    cmds:
      - npx tsx src/tasks/build.ts {{.FUNC}}
    generates:
      - dist/funcs/{{.FUNC}}/*.mjs

  build-all:
    desc: build all funcs.
    vars:
      FUNC_NAMES:
        sh: |
          # ls -d src/funcs/*/
          npx tsx src/tasks/find-funcs.ts
    sources:
      - src/funcs/**/*.ts
    cmds:
      - for: {var: FUNC_NAMES}
        task: build:{{.ITEM}}
    generates:
      - dist/funcs/**/*.mjs

  rebuild:*:
    desc: rebuild specific func (* is func name).
    vars:
      FUNC: '{{index .MATCH 0}}'
    deps: 
      - clean:{{.FUNC}}
    cmds:
      - task: build:{{.FUNC}}

  rebuild-all:
    desc: rebuild all funcs.
    deps: 
      - clean-all
    cmds:
      - task: build-all

  package:*:
    desc: package specific func (* is func name).
    vars:
      FUNC: '{{index .MATCH 0}}'
    requires:
      vars: [FUNC]
    deps: 
      - build:{{.FUNC}}
    sources:
      - dist/funcs/{{.FUNC}}/*.mjs
    cmds:
      - npx tsx src/tasks/package.ts {{.FUNC}}
    generates:
      - dist/packages/{{.FUNC}}.zip

  package-all:
    desc: package all funcs.
    vars:
      FUNC_NAMES:
        sh: npx tsx src/tasks/find-funcs.ts
    cmds:
      - for: {var: FUNC_NAMES}
        task: package:{{.ITEM}}

  sync-from-repo:*:
    desc: s3 sync checksum from func package repository to local (* is func name).
    vars:
      FUNC: '{{index .MATCH 0}}'
    requires:
      vars: [FUNC]
    cmds:
      - npx tsx src/tasks/sync-from-repo.ts {{.FUNC}}
    silent: true

  upload:*:
    desc: upload specific func (* is func name).
    vars:
      FUNC: '{{index .MATCH 0}}'
    requires:
      vars: [FUNC]
    deps: 
      - package:{{.FUNC}}
      - sync-from-repo:{{.FUNC}}
    sources:
      - dist/packages/{{.FUNC}}.zip
    cmds:
      - npx tsx src/tasks/upload.ts {{.FUNC}}
    generates:
      - dist/uploads/{{.LAMBDA_VERSION}}/{{.FUNC}}.zip.checksum

  upload-all:
    desc: upload all funcs to S3.
    vars:
      FUNC_NAMES:
        sh: npx tsx src/tasks/find-funcs.ts
    cmds:
      - for: {var: FUNC_NAMES}
        task: upload:{{.ITEM}}

  sync-from-code:*:
    desc: lambda sync code's sha256 from lambda to local (* is func name).
    vars:
      FUNC: '{{index .MATCH 0}}'
    requires:
      vars: [FUNC]
    cmds:
      - npx tsx src/tasks/sync-from-code.ts {{.FUNC}}
    silent: true

  deploy:*:
    desc: deploy specific func (* is func name).
    vars:
      FUNC: '{{index .MATCH 0}}'
    requires:
      vars: [FUNC]
    deps: 
      - upload:{{.FUNC}}
      - sync-from-code:{{.FUNC}}
    sources:
      - dist/uploads/{{.LAMBDA_VERSION}}/{{.FUNC}}.zip.checksum
    cmds:
      - npx tsx src/tasks/deploy.ts {{.FUNC}}
    generates:
      - dist/deploys/{{.WORKLOAD}}/{{.FUNC}}-{{.WORKLOAD}}.codesha256

  deploy-all:
    desc: deploy all funcs in Lambda.
    vars:
      FUNC_NAMES:
        sh: npx tsx src/tasks/find-funcs.ts
    cmds:
      - for: {var: FUNC_NAMES}
        task: deploy:{{.ITEM}}

  logs:*:
    desc: get logs for specific func (* is func name).
    vars:
      FUNC: '{{index .MATCH 0}}'
      RECENT: '{{.RECENT| default 8}}'
      LIMIT: '{{.LIMIT| default 10}}'
      FILTER: '{{.FILTER| default ""}}'
    requires:
      vars: [FUNC]
    cmds:
      - npx tsx src/tasks/logs.ts {{.FUNC}} --recent-hours={{.RECENT}} --request-limit={{.LIMIT}} --filter-pattern={{.FILTER}}
    
  query:*:
    desc: query logs insight for specific func (* is func name).
    vars:
      FUNC: '{{index .MATCH 0}}'
      Q: '{{.Q| default "fields @timestamp, @message"}}'
      RECENT: '{{.RECENT| default 1}}'
      FILTER: '{{.FILTER| default ""}}'
      NO_FILTER: '{{.NO_FILTER| default false}}'
    requires:
      vars: [FUNC]
    cmds:
      - npx tsx src/tasks/logs-query.ts {{.FUNC}} --query="{{.Q}}" --recent-days={{.RECENT}} --filter-pattern="{{.FILTER}}" --no-filter={{.NO_FILTER}}
